name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger info
        run: echo " The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Runner info
        run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Repo info
        run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Run Python script
        run: python job.py
